apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../services/quest-service/k8s

patches:
- path: patch-env.yml
- path: patch-resources.yml

images:
- name: quest-service
  # newName: ghcr.io/mhs-20/quest-service
  # newTag: b0e526ffefcbe501118caaced29b87203a8187f7
  newName: quest-service
  newTag: latest

replicas:
- count: 1
  name: quest-service
