apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../services/quest-service/k8s

patches:
- path: patch-env.yml
- path: patch-resources.yml

  # newName: ghcr.io/mhs-20/quest-service
  # newTag: b0e526ffefcbe501118caaced29b87203a8187f7
images:
- name: quest-service
  newName: ghcr.io/ghcr.io/mhs-20/habitquest/quest-service/quest-service

replicas:
- count: 1
  name: quest-service
