apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/MHS-20/habitquest/edge-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-ingress.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/mhs-20/habitquest/edge-service
  newTag: 21f5d4d46da941ffb5cd46bc8b917665a4ef4351

replicas:
- count: 1
  name: edge-service
