server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: guild-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/habitquestdb_guild
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  #  flyway:
  #    user: ${spring.r2dbc.username}
  #    password: ${spring.r2dbc.password}
  #    url: jdbc:postgresql://localhost:5432/habitquestdb_guild
  config:
    import: ""

  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    function:
      definition: guild

    stream:
      bindings:
        guild-created-out-0:
          destination: guild.created
          content-type: application/json

        guild-deleted-out-0:
          destination: guild.deleted
          content-type: application/json

        guild-joined-out-0:
          destination: guild.joined
          content-type: application/json

        guild-left-out-0:
          destination: guild.left
          content-type: application/json

        guild-removed-out-0:
          destination: guild.member-removed
          content-type: application/json

        guild-role-assigned-out-0:
          destination: guild.role-assigned
          content-type: application/json

        guild-battle-started-out-0:
          destination: guild.battle-started
          content-type: application/json

        guild-battle-won-out-0:
          destination: guild.battle-won
          content-type: application/json

        guild-battle-lost-out-0:
          destination: guild.battle-lost
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
            acks: all
            retries: 3
            enable.idempotence: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/HabitQuest

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: HabitQuest

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

avatar:
  service-uri: "http://localhost:8080"