apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/MHS-20/habitquest/marketplace-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: marketplace-config

images:
- name: marketplace-service
  newName: ghcr.io/ghcr.io/mhs-20/habitquest/marketplace-service/marketplace-service
  newTag: marketplace-v1.0.1

replicas:
- count: 1
  name: marketplace-service
