apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatar-service
spec:
  template:
    spec:
      containers:
        - name: avatar-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: habitquest-postgres-avatar-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret
