server:
  port: 8086

info:
  system: habitquest

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

################## KAFKA ##################
  cloud:
    function:
      definition: avatarLevelUpped;avatarDead;avatarSkillPointAssigned;avatarNewSpellLearned;guildBattleStarted;guildBattleWon;guildBattleLost;guildCreated;guildDeleted;guildJoined;guildLeft;guildRemoved;guildRoleAssigned;guildInviteSent;marketplaceItemBought;marketplaceItemSold;questCreated;questCompleted;questNotCompleted;questJoined;questLeft;habitDeleted;habitAttended;habitNotAttended;userRegistered
    stream:
      bindings:
        avatarLevelUpped-in-0:
          destination: avatar.level-upped
          group: notification-service
        avatarDead-in-0:
          destination: avatar.dead
          group: notification-service
        avatarSkillPointAssigned-in-0:
          destination: avatar.skill-point-assigned
          group: notification-service
        avatarNewSpellLearned-in-0:
          destination: avatar.new-spell-learned

        guildBattleStarted-in-0:
          destination: guild.battle-started
          group: notification-service
        guildBattleWon-in-0:
          destination: guild.battle-won
          group: notification-service
        guildBattleLost-in-0:
          destination: guild.battle-lost
          group: notification-service

        guildCreated-in-0:
          destination: guild.created
          group: notification-service
        guildDeleted-in-0:
          destination: guild.deleted
          group: notification-service
        guildJoined-in-0:
          destination: guild.joined
          group: notification-service
        guildLeft-in-0:
          destination: guild.left
          group: notification-service
        guildRemoved-in-0:
          destination: guild.removed
          group: notification-service
        guildRoleAssigned-in-0:
          destination: guild.role-assigned
          group: notification-service
        guildInviteSent-in-0:
          destination: guild.invite-sent
          group: notification-service

        marketplaceItemBought-in-0:
          destination: marketplace.item-bought
          group: notification-service
        marketplaceItemSold-in-0:
          destination: marketplace.item-sold
          group: notification-service

        questCreated-in-0:
          destination: quest.created
          group: notification-service
        questCompleted-in-0:
          destination: quest.completed
          group: notification-service
        questNotCompleted-in-0:
          destination: quest.not-completed
          group: notification-service
        questJoined-in-0:
          destination: quest.joined
          group: notification-service
        questLeft-in-0:
          destination: quest.left
          group: notification-service

        habitDeleted-in-0:
          destination: habit.deleted
          group: notification-service
        habitAttended-in-0:
          destination: habit.attended
          group: notification-service
        habitNotAttended-in-0:
          destination: habit.not-attended
          group: notification-service

        userRegistered-in-0:
          destination: user.registered
          group: notification-service
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:localhost:9092}

############ OBSERVABILITY #############
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  structured:
    format:
      console: ecs

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers, retries, bindings, configprops, env, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
    observations:
      key-values:
        http.server.requests:
          enabled: true

  otlp:
    metrics:
      export:
        url: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318}/v1/metrics
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318}/v1/traces

  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    tags:
      application: ${spring.application.name}

  health:
    kafka:
      enabled: true