apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
spec:
  template:
    spec:
      containers:
        - name: tracking-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: AVATAR_SERVICE_URI
              value: http://avatar-service:8081
            - name: KAFKA_BROKER
              value: kafka-service:9092
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: http://tempo.prometheus-system.svc.cluster.local:4318
