build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    threshold: 10
    ignoreDefaultParameters: true
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'

style:
  MagicNumber:
    ignoreAnnotated: ['Composable', 'Preview']
  ReturnCount:
    active: false